---
# tasks file for db-tier
# tasks file for postgres_install
- name: install postgres
  yum:
    name: postgresql-server
    state: latest
  register: pg_install
  notify: restart_postgres

- name: check if data directory exists
  stat:
    path: /var/lib/pgsql/data
  register: pg_datapath

- name: initilize postgres
  command: postgresql-setup initdb
  when: not pg_datapath.stat.exists or pg_install is changed
  notify: restart_postgres
      